server:
  port: 80
  sources:
    - path: "/host"
      config:
        defaultEnabled: true
      name: "Host"
    - path: "/volumes"
      config:
        defaultEnabled: true
      name: "ServApp Volumes"

auth:
  methods:
    proxy:
      enabled: true
      header: "X-Cosmos-User"
      createUser: true

frontend:
  name: "Quantum Filebrowser"
 
userDefaults:
  preview:
    highQuality: true
    image: true
    video: true
    motionVideoPreview: true
    office: true
    popup: true
    folder: true
  permissions:
    api: false
    admin: false
    modify: true
    share: false
    realtime: false
    delete: true
    create: true
    download: true
  disableOnlyOfficeExt: ".md .txt .pdf"   # list of file extensions to disable onlyoffice editor for